# Generated by Django 5.1.4 on 2024-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camada',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
