# Generated by Django 5.1.4 on 2024-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_camada_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camada',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
